// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcvxphhzrqksdmlniozx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjdnhwaGh6cnFrc2RtbG5pb3p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMTI4NjQsImV4cCI6MjA1OTU4ODg2NH0.9DDJxZTu1XcaWQHdww1hAg8lmBuqPjMp_OtKi-Y1xl4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

export const getProjectsData = async (
  startDate: string,
  endDate: string,
  projectId?: string
) => {
  try {
    const { data, error } = await supabase.rpc('get_energy_data', {
      p_date_range: 'custom',
      p_start_date: startDate,
      p_end_date: endDate
    });

    if (error) {
      console.error('Error fetching projects data:', error);
      throw error;
    }

    // Convert timestamps to Date objects for frontend use
    const processedData = Array.isArray(data) ? data.map((item: any) => ({
      ...item,
      timestamp: new Date(item.timestamp),
      created_at: new Date(item.created_at),
      updated_at: new Date(item.updated_at)
    })) : [];

    return processedData;
  } catch (error) {
    console.error('Error in getProjectsData:', error);
    throw error;
  }
};
