// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcvxphhzrqksdmlniozx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjdnhwaGh6cnFrc2RtbG5pb3p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMTI4NjQsImV4cCI6MjA1OTU4ODg2NH0.9DDJxZTu1XcaWQHdww1hAg8lmBuqPjMp_OtKi-Y1xl4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);